# ===================== 行情周期参数 =====================
RECENT_DAY = 10
HOT_SCORE_THRESHOLD = 60
LEADER_NUM = 3

# 基础过滤
FILTER_ST = True
MIN_CAP = 50
MAX_TURN_RATE = 22
MIN_TURN_RATE = 2
MIN_DAILY_AMOUNT = 1.2 # 日均成交额 亿

# 均线参数
SHORT_MA = 20
MID_MA = 60

# 龙头打分权重
WEIGHT_INCREASE = 35
WEIGHT_VOLUME = 25
WEIGHT_LIMIT_UP = 20
WEIGHT_NORTH_MONEY = 15
WEIGHT_TURNOVER = 5

# 请求控制
MIN_SLEEP = 0.25
MAX_SLEEP = 0.8
RETRY_TIMES = 3

# 利空公告筛查天数
NEWS_CHECK_DAY = 15

# 形态识别参数
N_AMPLITUDE_THRESHOLD = 0.12
BOX_WINDOW = 45
